[theme]
primaryColor = "#00ff00"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 200

[browser]
gatherUsageStats = false
